#!/bin/bash

kathara lstart
sleep 5

xdotool search --name "root@pc1: /" windowmove 0    0
xdotool search --name "root@pc2: /" windowmove 500  0
xdotool search --name "root@pc3: /" windowmove 0    350
xdotool search --name "root@pc4: /" windowmove 500    350

xdotool search --name "root@router1: /" windowmove 0    700
xdotool search --name "root@router2: /" windowmove 500  700
xdotool search --name "root@router3: /" windowmove 1000 700

chromium --app=http://localhost:3000 --new-window &
