#!/bin/bash

kathara lstart
echo "Waiting for startup of all network nodes..."
sleep 5

xdotool search --name "root@pc1_subnet1: /" windowmove 0 0
xdotool search --name "root@pc2_subnet1: /" windowmove 1000 0
xdotool search --name "root@pc3_subnet1: /" windowmove 2000 0
xdotool search --name "root@router1: /"     windowmove 3000 0

xdotool search --name "root@pc1_subnet2: /" windowmove 0 350
xdotool search --name "root@pc2_subnet2: /" windowmove 1000 350
xdotool search --name "root@pc3_subnet2: /" windowmove 2000 350
xdotool search --name "root@router2: /"     windowmove 3000 350

xdotool search --name "root@pc1_subnet3: /" windowmove 0 700
xdotool search --name "root@pc2_subnet3: /" windowmove 1000 700
xdotool search --name "root@pc3_subnet3: /" windowmove 2000 700
xdotool search --name "root@router3: /"     windowmove 3000 700

echo "Success"
